---
script: "make all"
language: erlang
sudo: false
install: "true" # don't let travis run get-deps
otp_release:
  - 19.1
  - 18.3
  - 17.5
  - R16B03-1
## These won't work until we have checks for application:ensure_all_started
#  - R15B03
#  - R14B04
